### ISSUE TITLE
Allow non-git repositories as advisory databases

### ISSUE THREAD

**Issue by nmattia** [RustSec/rustsec-crate#132]
It's my understanding that `cargo-audit` only supports git repositories as advisory databases. Even if `no_fetch` is set, `cargo audit` still calls [`Repository::open()`](https://github.com/RustSec/rustsec-crate/blob/7726548e312ec81b24252769bccaa8da6d48bae6/src/repository.rs#L156).

I have a use case where I have a non-git repository as an advisory database. For now I'll try creating a dummy git repo before running `cargo audit`.

**Comment by tarcieri** [comment]
You can read some of the history of why a git repository was used here:

https://github.com/RustSec/cargo-audit/issues/163#issuecomment-553955651

Perhaps with a suitable low-dependency HTTP client (e.g. `ureq`) it would be possible to support HTTP as an alternative.

**Comment by nmattia** [comment]
Thanks for the background!

I'm talking about the `--db` argument; I'd like to be able to point it to a directory that _may not be_ a git repository. Right now I run `git init; git add -A; git commit -m "dummy"` so that `Repository::open()` doesn't fail on it.

**Comment by tarcieri** [comment]
Aah, interesting. I can look into that.

**Comment by tarcieri** [comment]
This should be addressed by #213

**Comment by nmattia** [comment]
Thanks, I'll try it out!
