### ISSUE TITLE
can't import crate

### ISSUE THREAD

**Issue by mimoo** [RustSec/rustsec-crate#293]
Hey hey,

I can't seem to import this crate and use it without an error:

```
error: failed to select a version for `smol_str`.
    ... required by package `rustsec v0.23.0`
    ... which is depended on by `test_rustsec v0.1.0 (/Users/davidwg/Desktop/test_rustsec)`
versions that meet the requirements `=0.1.17` are: 0.1.17

all possible versions conflict with previously selected packages.

  previously selected package `smol_str v0.1.16`
    ... which is depended on by `cargo-audit v0.13.1`
    ... which is depended on by `test_rustsec v0.1.0 (/Users/davidwg/Desktop/test_rustsec)`

failed to select a version for `smol_str` which could resolve this conflict
```

**Comment by tarcieri** [comment]
Are you trying to use `cargo-audit` as a library? There's not a lot of reason to do that.

Regardless, it looks like you're using two incompatible versions. You need to use `rustsec` v0.22 in that case because `cargo-audit` hasn't yet been upgraded to `rustsec` v0.23.

**Comment by mimoo** [comment]
Yeah I actually was : ) I'm writing a tool that parses the result of `cargo-audit`, and I realize that instead of running the command on the CLI I could just run 

```rust
    let mut audit_config = AuditConfig::default();
    audit_config.output.format = OutputFormat::Json;
    let mut auditor = Auditor::new(&audit_config);
    let report = auditor.audit(Some(&repo_path.join("Cargo.lock")));
```

**Comment by tarcieri** [comment]
Yeah, `cargo-audit` is pretty much a shell around the `rustsec` crate.

You can also look at `cargo-deny` as an example of another tool which has integrated it.

**Comment by mimoo** [comment]
I ended up digging a bit in all three crates and both cargo-audit and rustsec are super readable! All good thanks : )
