### ISSUE TITLE
Make patch release?

### ISSUE THREAD

**Issue by Jake-Shadle** [RustSec/rustsec-crate#300]
https://github.com/RustSec/rustsec-crate/commit/2e117809661fadd47faaed1e82078bdff9015e90 fixed a windows specific issue, but isn't released yet, which is actually blocking me from releasing a new version of cargo-deny as I (sadly) support Windows as a primary host platform.

**Comment by tarcieri** [comment]
v0.23.1 released in #301

**Comment by Jake-Shadle** [comment]
Thanks!
