### ISSUE TITLE
Unaffected crates are still flagged as vulnerabilities 

### ISSUE THREAD

**Issue by MF1-MS** [RustSec/rustsec-crate#51]
This was come across as the presence of `crossbeam` v0.2.12 causes `cargo audit` to fail, despite the only affected version being v0.4.0, see: https://github.com/RustSec/advisory-db/blob/master/crates/crossbeam/RUSTSEC-2018-0009.toml

From a brief look at the code it seems that `unaffected_versions` needs to be stripped out like `patched_versions` in [db.rs](https://github.com/RustSec/rustsec-crate/blob/316f71c9a69ad50401f960902e459de8f7471a3f/src/db.rs#L114)

**Comment by tarcieri** [comment]
Well that's unfortunate. I'll try to get a quick fix out for this.

**Comment by MF1-MS** [comment]
Cracking, many thanks.
