### ISSUE TITLE
Implement https proxy support

### ISSUE THREAD

**Issue by jsgf** [RustSec/rustsec-crate#94]
Rustsec does not appear to support configuring git2 to use an https proxy to access the git repo. I would imagine many environments wanting to use this crate would be required to do so via an https proxy.

In the meantime I can separately vendor the advisory-db repo, but it would be nice to be able to fetch it live as well.

**Comment by tarcieri** [comment]
I think the best way to address this and #62 is offer something along the lines of Cargo's `net.git-fetch-with-cli = true` which (optionally) shells out to the `git` CLI to perform updates, allowing you to leverage whatever features it supports.
